#!/bin/sh

[ -f "$1" ] && cp "$1" ~/.config/wallpaper.png && notify-send -i "$HOME/.config/wallpaper.png" "Wallpaper changed"

[ -d "$1" ] && \
    mv "$(find "$1" -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -type f | shuf -n 1)" ~/.config/wallpaper.png && \
    notify-send -i "$HOME/.config/wallpaper.png" "Random wallpaper selected."

xwallpaper --center ~/.config/wallpaper.png
